apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tyk-gw-secrets
  namespace: tyk
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: mach-kv-dev-store
  target:
    name: tyk-gw-secrets
    creationPolicy: Owner
  data:
  - secretKey: apiKey
    remoteRef:
      key: TYK-API-KEY
  - secretKey: APISecret
    remoteRef:
      key: TYK-API-SECRET
  - secretKey: rpcKey
    remoteRef:
      key: TYK-RPC-KEY
  - secretKey: redisPass
    remoteRef:
      key: TYK-REDIS-PASSWORD
  - secretKey: redisSentinelPass
    remoteRef:
      key: TYK-REDIS-SENTINAL-PASSWORD
  - secretKey: mongoURL
    remoteRef:
      key: TYK-MONGO-CONNECTIONSTRING


