apiVersion: v1
kind: ConfigMap
metadata:
  name: hybrid-gateway-conf-{{ include "tyk-hybrid.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: gateway-{{ include "tyk-hybrid.fullname" . }}
    chart: {{ include "tyk-hybrid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- (.Files.Glob "configs/tyk_hybrid.conf").AsConfig | nindent 2 }}
