helmCharts:
- releaseName: redis
  namespace: tyk
  includeCRDs: true
  name: redis
  version: 17.8.2
  repo: https://charts.bitnami.com/bitnami
  valuesInline:
    auth:
      sentinel: true
      existingSecret: tyk-gw-secrets
      existingSecretPasswordKey: redisPass
    sentinel:
      enabled: true
